repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff lint
        entry: poetry run ruff check --fix --exit-non-zero-on-fix
        language: python
        types_or: [python, pyi]
        require_serial: true
        stages: [pre-commit]

      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format
        language: python
        types_or: [ python, pyi ]
        require_serial: true
        stages: [pre-commit]

      - id: mypy
        name: mypy
        entry: poetry run mypy
        language: python
        types_or: [ python, pyi ]
        stages: [pre-push]

      - id: tests
        name: tests
        entry: poetry run pytest
        language: python
        stages: [pre-push]
