name: docs

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:


jobs:
  build:
    name: build documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip
      - name: update pip
        run: pip install --upgrade pip
      - name: install poetry
        run: pip install poetry
      - name: install docs dependencies
        run: poetry install --only docs
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: build docs with mkdocs
        run: cd docs && poetry run mkdocs gh-deploy --force
