name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"


jobs:
  pypi-publish:
    name: Publish to Pypi
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: update pip
        run: pip install --upgrade pip
      - name: install poetry
        run: pip install poetry
      - name: Extract Tag Name
        run: echo "TAG_NAME=$(git describe --tags --exact-match HEAD)" >> $GITHUB_ENV
      - name: display tag version
        run: echo "new version $TAG_NAME"
      - uses: ./.github/workflows/generate-changelog.yml
        with:
          tag: "$TAG_NAME"
#      - name: update version
#        run: poetry version $TAG_NAME
#      - name: publish
#        run: poetry publish --build
#        env:
#           POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
